baseURL: "https://yuminghuo.github.io"
languageCode: en-us
title: Yuming Huo
theme: PaperMod
defaultContentLanguage: en
defaultContentLanguageInSubdir: true

languages:
  en:
    languageName: "English"
    languageCode: "en"
    contentDir: "content/English"
    menu:
      main:
        - identifier: search
          name: Search
          url: /search/
          weight: 50
    params:
      defaultTheme: dark
      ShowShareButtons: false
      ShowReadingTime: true
      author: ["Yuming"]
      ShowBreadCrumbs: true
      ShowPostNavLinks: true
      profileMode:
        enabled: true
        title: "Yuming Huo"
        subtitle: "University of Bristol"
        imageUrl: "img/title.JPG"
        imageTitle: "Yuming Huo"
        imageWidth: 120
        imageHeight: 120
        buttons:
          - name: About me
            url: "/en/about/"
          - name: My project
            url: "/en/project/"
          - name: My intership
            url: "/en/inter/"
          - name: Resume
            url: "/pdf/Yuming Huo.pdf"
      socialIcons:
        - name: "Github"
          url: "https://github.com/YumingHuo"
        - name: "email"
          url: "mailto:hym811@outlook.com"
        - name: "Discord"
          url: "https://discordapp.com/users/huoh"
    
    # permalinks:
    #   about: "/chinese/about/"
    #   project: "/chinese/project/"
    #   inter: "/english/inter/"


  zh:
    languageName: "ä¸­æ–‡"
    languageCode: "zh"
    contentDir: "content/Chinese"
    menu:
      main:
        - identifier: search
          name: æœç´¢ğŸ”
          url: /search/
          weight: 50
    params:
      defaultTheme: dark
      ShowShareButtons: false
      ShowReadingTime: true
      author: ["Yuming"]
      ShowBreadCrumbs: true
      ShowPostNavLinks: true
      profileMode:
        enabled: true
        title: "éœç¦¹é“­"
        subtitle: "å¸ƒé‡Œæ–¯æ‰˜å¤§å­¦ è®¡ç®—æœºç§‘å­¦ æœ¬ç§‘"
        imageUrl: "img/title.JPG"
        imageTitle: "Yuming Huo"
        imageWidth: 120
        imageHeight: 120
        buttons:
          - name: About me
            url: "/zh/about/"
          - name: My project
            url: "/zh/project/"
          - name: My intership
            url: "/zh/inter/"
          - name: ç®€å†
            url: "/pdf/éœç¦¹é“­.pdf"
      socialIcons:
        - name: "Github"
          url: "https://github.com/YumingHuo"
        - name: "email"
          url: "mailto:hym811@outlook.com"
        - name: "Discord"
          url: "https://discordapp.com/users"

    # permalinks:
    #   about: "/chinese/about/"
    #   project: "/chinese/project/"
    #   inter: "/chinese/inter/"